name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: create venv
      run: python -m venv venv
    - name: install dependecies
      run: source venv/bin/activate && pip install -r requirements.txt
    - name: run in dev mode
      run: cd ./ELK && sudo docker compose up -d && cd .. && sudo docker compose up -d
    
