name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: create venv
      run: python -m venv venv
      
    - name: install dependecies
      run: source venv/bin/activate && pip install -r requirements.txt
      
  test: 
    runs-on: ubuntu-latest
    env:
      ENV: Dev
    steps:
    - name: run containers in dev mode
      working-directory: ./AriaStack_Ansible/AriaStack
      run: sh run_stack.sh
      
    - name: stop containers in dev mode
      working-directory: ./AriaStack_Ansible/AriaStack
      run: sh down_stack.sh
      
  deploy:
    runs-on: ubuntu-latest
    env:
      ENV: Production









      
